module: '''autogoal_sklearn._generated.SGDClassifier'''
name: SGDClassifier
params:
  average: true
  early_stopping: true
  epsilon: 0.22761636263344476
  eta0: -0.992
  fit_intercept: true
  l1_ratio: 0.999
  learning_rate: optimal
  loss: squared_hinge
  n_iter_no_change: 9
  penalty: elasticnet
  power_t: 4.991
  shuffle: true
  tol: -0.005
  validation_fraction: 0.006
